name: λ Thinking Test

on: [push, pull_request]

jobs:
  run-thinking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install -e .
          pip install pytest

      - name: Run λ engine
        run: |
          python -m lambda_lib.cli run examples/classifier/seed.yaml --steps 2000

      - name: Check reward grew
        run: |
          python tests/verify_reward_growth.py
